/* icon assets by fontawesome6 library */
// 6C757D
// 0CBBF0

const uriIcons = '../../../assets/icons/';
export const Assets = {
  icons: {
    delete: require(uriIcons + 'delete.png'),
    hashTag: require(uriIcons + 'hashtags.png'),
    tagUser: require(uriIcons + 'tag-user.png'),
    playVideo: require(uriIcons + 'play-video.png'),
    videoGallery: require(uriIcons + 'video-gallery.png'),
    home: require(uriIcons + 'home.png'),
    homeSelected: require(uriIcons + 'home-selected.png'),
    message: require(uriIcons + 'message.png'),
    messageSelected: require(uriIcons + 'message-selected.png'),
    notification: require(uriIcons + 'notification.png'),
    notificationSelected: require(uriIcons + 'notification-selected.png'),
    setting: require(uriIcons + 'setting.png'),
    settingSelected: require(uriIcons + 'setting-selected.png'),
    search: require(uriIcons + 'search.png'),
    heart: require(uriIcons + 'heart.png'),
    heartFill: require(uriIcons + 'heart-fill.png'),
    arrowLeft: require(uriIcons + 'arrow-left.png'),
    close: require(uriIcons + 'close.png'),
    eyeClose: require(uriIcons + 'eye-close.png'),
    eye: require(uriIcons + 'eye.png'),
    user: require(uriIcons + 'user.png'),
    earth: require(uriIcons + 'earth.png'),
    logout: require(uriIcons + 'logout.png'),
    translate: require(uriIcons + 'translate.png'),
    edit: require(uriIcons + 'edit.png'),
    location: require(uriIcons + 'location.png'),
    gender: require(uriIcons + 'gender.png'),
    term: require(uriIcons + 'term.png'),
    privacy: require(uriIcons + 'privacy.png'),
    theme: require(uriIcons + 'theme.png'),
    birthday: require(uriIcons + 'birthday.png'),
    camera: require(uriIcons + 'camera.png'),
    video: require(uriIcons + 'video.png'),
    gallery: require(uriIcons + 'gallery.png'),
    share: require(uriIcons + 'share.png'),
    option: require(uriIcons + 'options.png'),
    menu: require(uriIcons + 'menu.png'),
    comment: require(uriIcons + 'chat.png'),
    send: require(uriIcons + 'send.png'),
    follow: require(uriIcons + 'plus.png'),
    change: require(uriIcons + 'shuffle.png'),
    trash: require(uriIcons + 'trash.png'),
    graduation: require(uriIcons + 'graduation.png'),
    zodiac: require(uriIcons + 'zodiac.png'),
    male: require(uriIcons + 'male.png'),
    female: require(uriIcons + 'female.png'),
    calendar: require(uriIcons + 'calendar.png'),
    hobby: require(uriIcons + 'hobby.png'),
    check: require(uriIcons + 'check.png'),
    call: require(uriIcons + 'call.png'),
    attach: require(uriIcons + 'attach.png'),
    voice: require(uriIcons + 'keyboardvoice.png'),
    public: require(uriIcons + 'public.png'),
    private: require(uriIcons + 'private.png'),
    add: require(uriIcons + 'add.png'),
  },
  image: {
    logo: require('../../../assets/images/logo.png'),
    github: require('../../../assets/images/github.png'),
    google: require('../../../assets/images/google.png'),
    avt: require('../../../assets/images/avt.png'),
    right_arrow: require('../../../assets/images/right_arrow.png'),
    share: require('../../../assets/images/share.png'),
    arrow_down: require('../../../assets/icons/arrow-down.png'),
    arrow_up: require('../../../assets/icons/arrow-up.png'),
    game: require('../../../assets/images/game.png'),
    sport: require('../../../assets/images/sport.png'),
    food: require('../../../assets/images/food.png'),
    travelling: require('../../../assets/images/travel.png'),
    technology: require('../../../assets/images/tech.png'),
    book: require('../../../assets/images/book.png'),
    film: require('../../../assets/images/film.png'),
    music: require('../../../assets/images/music.png'),
    pet: require('../../../assets/images/pet.png'),
    photo: require('../../../assets/images/camera.png'),
    vietnam: require('../../../assets/images/vietnam.png'),
    us: require('../../../assets/images/us.png'),
    uk: require('../../../assets/images/uk.png'),
    thailand: require('../../../assets/images/thailand.png'),
    laos: require('../../../assets/images/lao.png'),
    korea: require('../../../assets/images/korea.png'),
    japan: require('../../../assets/images/japan.png'),
    france: require('../../../assets/images/france.png'),
    cambodia: require('../../../assets/images/cambodia.png'),
    malaysia: require('../../../assets/images/malay.png'),
    nationality: require('../../../assets/images/nationality.png'),
  },
};
