import {StyleSheet} from 'react-native';
import {Fonts} from './Fonts';
import {Colors} from './Colors';

export const Typography = StyleSheet.create({
  title: {
    fontFamily: Fonts.nunitonSans.extrabold,
    fontSize: 30,
    fontStyle: 'normal',
    fontWeight: '800',
    // lineHeight: 18,
    letterSpacing: -0.17,
  },
  subTitle: {
    fontFamily: Fonts.nunitonSans.regular,
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 25,
    letterSpacing: -0.17,
  },
  navTitle: {
    fontFamily: Fonts.roboto.semibold,
    fontStyle: 'normal',
    fontSize: 19,
    fontWeight: '600',
    lineHeight: 22,
    color: Colors.black,
  },
  edtHint: {
    fontFamily: Fonts.inter.regular,
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '400',
  },
  edtValue: {
    fontFamily: Fonts.inter.regular,
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '400',
  },
  bsdTitle: {
    fontFamily: Fonts.inter.bold,
    fontSize: 24,
    fontStyle: 'normal',
    fontWeight: '700',
  },
  bsdDescription: {
    fontFamily: Fonts.inter.regular,
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 25,
  },
  cPostHint: {
    fontFamily: Fonts.nunitonSans.regular,
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 8,
  },
  postTitle: {
    fontFamily: Fonts.nunitonSans.bold,
    fontSize: 15,
    fontStyle: 'italic',
    fontWeight: '700',
    letterSpacing: 0.5,
    textTransform: 'capitalize',
    color: Colors.black,
    lineHeight: 22,
  },
  postContent: {
    fontFamily: Fonts.nunitonSans.semibold,
    fontSize: 15,
    fontStyle: 'normal',
    fontWeight: '600',
    lineHeight: 21,
    color: Colors.black,
  },
  postName: {
    fontFamily: Fonts.nunitonSans.bold,
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 22,
    color: Colors.black,
  },
  cmtContent: {
    fontFamily: Fonts.nunitonSans.regular,
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '400',
    lineHeight: 22,
  },
  cmtName: {
    fontFamily: Fonts.nunitonSans.bold,
    fontSize: 16,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 22,
  },
  button: {
    fontFamily: Fonts.roboto.semibold,
    fontSize: 19,
    fontStyle: 'normal',
    fontWeight: '700',
    lineHeight: 22,
  },
  errorText: {
    fontSize: 12,
    color: Colors.error,
  },
  tagInf: {
    fontFamily: Fonts.inter.regular,
    fontSize: 15,
    lineHeight: 18,
  },
  typeInf: {
    fontFamily: Fonts.inter.bold,
    fontSize: 17,
  },
  privacySettingDesc: {
    fontFamily: Fonts.nunitonSans.regular,
    fontSize: 18,
    lineHeight: 24,
  },
  tagOptionSelected: {
    fontFamily: Fonts.nunitonSans.semibold,
    fontSize: 14,
    color: Colors.white,
  },
  tagOptionUnSelected: {
    fontFamily: Fonts.nunitonSans.regular,
    fontSize: 14,
    color: Colors.black,
  },
  smallTextInSearch: {
    fontFamily: Fonts.nunitonSans.regular,
    fontSize: 12,
  },
  searchAccountName: {
    fontFamily: Fonts.nunitonSans.bold,
    fontSize: 16,
    color: Colors.black,
  },
  userNotification: {
    fontFamily: Fonts.nunitonSans.bold,
    fontSize: 14,
    color: 'black',
  },
  contentNotification: {
    fontFamily: Fonts.nunitonSans.regular,
    fontSize: 14,
    color: 'black',
  },
  timeNotification: {
    fontFamily: Fonts.nunitonSans.regular,
    fontSize: 12,
    color: Colors.secondary,
  },
  followLabel: {
    fontFamily: Fonts.nunitonSans.regular,
    fontSize: 12,
    lineHeight: 14,
    color: Colors.black,
  },
  titleDialog: {
    fontFamily: Fonts.inter.bold,
    fontSize: 24,
    color: Colors.black,
  },
  descDialog: {
    fontFamily: Fonts.inter.regular,
    fontSize: 16,
    lineHeight: 20,
    color: Colors.secondary,
  },
  btnLabelDialog: {
    fontFamily: Fonts.inter.bold,
    fontSize: 20,
    color: Colors.white,
  },
  normalTextDialog: {
    fontFamily: Fonts.inter.regular,
    fontSize: 16,
    lineHeight: 19,
    color: Colors.black,
  },
  genderLabel: {
    fontFamily: Fonts.inter.bold,
    fontSize: 16,
  },
  derivedField: {
    fontFamily: Fonts.inter.bold,
    fontSize: 20,
    color: Colors.black,
  },
});
